# Predicting Student Mental Health Score from Social Media Usage

##### Problem: We're predicting a Student's Mental_Health_Score (a continuous score from ~3 to ~10) using their social media habits, study time, sleep, physical activity, and strees level. This is a regression problem since the target is a number, not a category.

##### Dataset: Student_Social_Media_And_Mental_Health_Impact.csv -- 5,000 students, 13 columns covering demographics (Age,Gende, Country), platform usage (Avg_Daily_Usage_Hours, Daily_Unlocks, Most_Used_Platform), lifestyle (Study_Hours,Sleep_Hours_Per_Night, Physical_Activity_Hours), and Stress_Level.

# Student Mental Health Prediction System

## Data Understanding

### Objective
The first phase of every Machine Learning project is to understand the dataset before performing any preprocessing or modeling

In this notebook, we will:

- Import the required libraries
- Load the dataset
- Display sample records
- Check the dataset dimensions
- View column names
- Understand the structure of the dataset

### 1. Import Libraries
We're grouping imports by purpose: data handaling, visualization, pre-processing, models, evaluation, and saving. 
Keeping imports grouped like this makes it easy to see at a glance what the notebook is going to do.

In [1]:
# Data Manipulation
import numpy as np
import pandas as pd

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Import the os module to work with file and folder paths
import os

# Check Current Working Directory
print(os.getcwd())

# Ignore warnings
import warnings
warnings.filterwarnings("ignore") # These two lines of code are used to completely hide and suppress all non-fatal warning messages generated by Python

d:\RUTU'S FOLDER\Rutu's_programing_ folder\Projects\Mental_Health_Prediction_System\Notebooks

### Observation

All the required libraries were imported successfully. These libraries will be used throughout the project for data analysis, visualization, preprocessing, and model development.

### 2. Load the Dataset


In this step, we load the dataset into a Pandas DataFrame. This allows us to access, explore, and analyze the data throughout the project.

In [ ]:
df = pd.read_csv("../Data/01_Raw/Student Social Media And Mental Health Impact.csv")

df

,Age,Gender,Country,Academic_Level,Most_Used_Platform,Purpose_Of_Use,Avg_Daily_Usage_Hours,Daily_Unlocks,Study_Hours,Physical_Activity_Hours,Sleep_Hours_Per_Night,Stress_Level,Mental_Health_Score
0,21,Male,Other,Undergraduate,Facebook,Networking,4.0,134,4.5,2.2,6.7,Medium,6.8
1,23,Female,Other,Graduate,LinkedIn,Education,1.6,73,7.0,2.4,8.6,Low,7.6
2,22,Male,Canada,Undergraduate,Instagram,Entertainment,4.6,166,4.0,1.8,6.7,Medium,7.0
3,18,Male,Other,High School,Snapchat,Entertainment,7.0,220,1.0,1.7,5.4,Very High,5.3
4,24,Female,Other,Graduate,Facebook,Networking,7.5,237,1.0,1.1,5.0,Very High,4.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,18,Female,Other,High School,YouTube,Education,1.9,89,6.1,2.2,7.9,Low,7.9
4996,18,Female,Other,High School,YouTube,Education,6.6,216,2.3,1.8,6.0,Very High,4.7
4997,19,Female,India,Undergraduate,LinkedIn,Education,3.8,151,5.4,1.4,7.5,Medium,7.0
4998,18,Male,Other,High School,Instagram,Entertainment,3.8,119,4.0,1.5,6.4,Medium,6.7
4999,19,Male,China,Undergraduate,WeChat,Entertainment,5.4,177,1.2,1.5,6.3,High,6.1

In [3]:
# Display the first five records
df.head()

,Age,Gender,Country,Academic_Level,Most_Used_Platform,Purpose_Of_Use,Avg_Daily_Usage_Hours,Daily_Unlocks,Study_Hours,Physical_Activity_Hours,Sleep_Hours_Per_Night,Stress_Level,Mental_Health_Score
0,21,Male,Other,Undergraduate,Facebook,Networking,4.0,134,4.5,2.2,6.7,Medium,6.8
1,23,Female,Other,Graduate,LinkedIn,Education,1.6,73,7.0,2.4,8.6,Low,7.6
2,22,Male,Canada,Undergraduate,Instagram,Entertainment,4.6,166,4.0,1.8,6.7,Medium,7.0
3,18,Male,Other,High School,Snapchat,Entertainment,7.0,220,1.0,1.7,5.4,Very High,5.3
4,24,Female,Other,Graduate,Facebook,Networking,7.5,237,1.0,1.1,5.0,Very High,4.4

In [4]:
# Display the last five rows of the dataset
df.tail()

,Age,Gender,Country,Academic_Level,Most_Used_Platform,Purpose_Of_Use,Avg_Daily_Usage_Hours,Daily_Unlocks,Study_Hours,Physical_Activity_Hours,Sleep_Hours_Per_Night,Stress_Level,Mental_Health_Score
4995,18,Female,Other,High School,YouTube,Education,1.9,89,6.1,2.2,7.9,Low,7.9
4996,18,Female,Other,High School,YouTube,Education,6.6,216,2.3,1.8,6.0,Very High,4.7
4997,19,Female,India,Undergraduate,LinkedIn,Education,3.8,151,5.4,1.4,7.5,Medium,7.0
4998,18,Male,Other,High School,Instagram,Entertainment,3.8,119,4.0,1.5,6.4,Medium,6.7
4999,19,Male,China,Undergraduate,WeChat,Entertainment,5.4,177,1.2,1.5,6.3,High,6.1

In [5]:
# Display the number of rows and columns in the dataset
df.shape

(5000, 13)

In [6]:
# Display detailed information about the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      5000 non-null   int64
 1   Gender                   5000 non-null   str
 2   Country                  5000 non-null   str
 3   Academic_Level           5000 non-null   str
 4   Most_Used_Platform       5000 non-null   str
 5   Purpose_Of_Use           5000 non-null   str
 6   Avg_Daily_Usage_Hours    5000 non-null   float64
 7   Daily_Unlocks            5000 non-null   int64
 8   Study_Hours              5000 non-null   float64
 9   Physical_Activity_Hours  5000 non-null   float64
 10  Sleep_Hours_Per_Night    5000 non-null   float64
 11  Stress_Level             5000 non-null   str
 12  Mental_Health_Score      5000 non-null   float64
dtypes: float64(5), int64(2), str(6)
memory usage: 736.5 KB

In [7]:
# Display the names of all columns in the dataset
df.columns.to_list()

['Age',
 'Gender',
 'Country',
 'Academic_Level',
 'Most_Used_Platform',
 'Purpose_Of_Use',
 'Avg_Daily_Usage_Hours',
 'Daily_Unlocks',
 'Study_Hours',
 'Physical_Activity_Hours',
 'Sleep_Hours_Per_Night',
 'Stress_Level',
 'Mental_Health_Score']

In [8]:
# Display the data type of each column
df.dtypes

Age                          int64
Gender                         str
Country                        str
Academic_Level                 str
Most_Used_Platform             str
Purpose_Of_Use                 str
Avg_Daily_Usage_Hours      float64
Daily_Unlocks                int64
Study_Hours                float64
Physical_Activity_Hours    float64
Sleep_Hours_Per_Night      float64
Stress_Level                   str
Mental_Health_Score        float64
dtype: object

In [9]:
# Generate descriptive statistics for numerical columns
df.describe()

,Age,Avg_Daily_Usage_Hours,Daily_Unlocks,Study_Hours,Physical_Activity_Hours,Sleep_Hours_Per_Night,Mental_Health_Score
count,5000.00000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,20.82180,5.078460,171.452600,3.008420,1.751000,6.634580,6.230980
std,1.73662,1.653913,42.858254,1.637018,0.668398,1.221391,1.278701
min,18.00000,1.000000,62.000000,0.300000,-0.400000,3.600000,3.600000
25%,19.00000,3.800000,140.000000,1.500000,1.300000,5.600000,5.100000
50%,21.00000,5.000000,171.000000,2.800000,1.700000,6.600000,6.100000
75%,22.00000,6.300000,204.000000,4.200000,2.200000,7.500000,7.100000
max,24.00000,8.800000,273.000000,8.300000,4.100000,9.900000,9.400000

In [10]:
# Display a random sample of records from the dataset
df.sample(5)

,Age,Gender,Country,Academic_Level,Most_Used_Platform,Purpose_Of_Use,Avg_Daily_Usage_Hours,Daily_Unlocks,Study_Hours,Physical_Activity_Hours,Sleep_Hours_Per_Night,Stress_Level,Mental_Health_Score
2003,20,Female,USA,Undergraduate,TikTok,Entertainment,7.0,201,1.2,1.1,5.6,Very High,4.9
4329,20,Female,South Korea,Undergraduate,KakaoTalk,Entertainment,4.6,162,5.0,1.5,7.2,High,6.3
135,24,Male,Other,Graduate,Instagram,Entertainment,3.7,141,4.3,2.0,7.4,Medium,8.7
952,21,Female,Other,Undergraduate,Twitter,News,6.2,218,1.0,1.2,5.4,Very High,5.4
1247,22,Male,Germany,Undergraduate,Instagram,Entertainment,3.9,158,3.2,1.8,7.8,Medium,8.0

### Observation :

- The dataset contains **5000 rows and 13 columns**.
- There are **7 numerical columns and 6 categorical** columns related to demographics, social media usage, lifestyle, stress, and mental health, in the dataset.
- The **average age** of students is around **21 years**.
- The average study time is around **3 hours** per day.
- The average daily social media usage is around **5 hours**.
- The average mental health score is around **6.2**.
- Data quality issues like **negative values in physical activity hours** need to be handled during data cleaning.

## Missing Values Check:

In [11]:
# Check the missing values and sum of missing values for each column
df.isnull().sum()

Age                        0
Gender                     0
Country                    0
Academic_Level             0
Most_Used_Platform         0
Purpose_Of_Use             0
Avg_Daily_Usage_Hours      0
Daily_Unlocks              0
Study_Hours                0
Physical_Activity_Hours    0
Sleep_Hours_Per_Night      0
Stress_Level               0
Mental_Health_Score        0
dtype: int64

## Duplicate check:

In [12]:
# Check the total number of duplicate rows present in the dataset
df.duplicated().sum()

np.int64(2)

## Observation :

- **No missing values** values are present in the dataset.
- There are only **2 duplicate records** which will be removed during data cleaning.
- Data cleaning and preprocessing steps will be performed in the next phase.

## Dataset Understanding Completed !